witesand/osm

init-iptables.sh
pkg/envoy/cds/cluster.go
ws/build.sh
ws/run.sh

first osm commit

---

ws/build.sh

removed bin/osm

---

charts/osm/values.yaml
dockerfiles/Dockerfile.osm-controller
init-iptables.sh
pkg/certificate/providers/tresor/types.go

Using 2K-bit cert instead of 4K-bit

after using 2048-bit cert

---

charts/osm/values.yaml
init-iptables.sh
pkg/envoy/cds/cluster.go

some changes from OSM-repo

---

pkg/catalog/routes.go
pkg/catalog/types.go
pkg/envoy/cds/cluster.go
pkg/envoy/cds/response.go
pkg/envoy/cla/cluster_load_assignment.go
pkg/envoy/eds/response.go
pkg/envoy/rds/response.go
pkg/envoy/sds/response.go
pkg/service/types.go
pkg/tests/fixtures.go
pkg/trafficpolicy/types.go

patching multi-port changes

---

pkg/envoy/rds/response.go

fixing an issue with apiserver, mainly for NodePort versions

---

init-iptables.sh

iptables changes

---

cmd/osm-controller/osm-controller.go
dockerfiles/Dockerfile.osm-controller
init-iptables.sh
pkg/catalog/xds_certificates.go
pkg/injector/init-container.go

osm rest fixes

---

init-iptables.sh

iptables rules for sims

---

init-iptables.sh

iptables fix

---

init-iptables.sh

commenting -X from iptables

---

init-iptables.sh

more radiusconf related port

---

.env
init-iptables.sh

adding port 9128 for historyd

---

.env
init-iptables.sh

adding netconf port for juniper

---

README.md
README.md.old
pkg/catalog/xds_certificates.go
ws/build.sh

rest api fixes

---

init-iptables.sh
ws/build.sh

adding alertdispatch rules

---

init-iptables.sh
ws/build.sh

nlp rest port fixes

---

init-iptables.sh
ws/build.sh

presto fixes in iptables

---

init-iptables.sh
ws/build.sh

aruba ports

---

pkg/envoy/lds/connection_manager.go
ws/build.sh

osm stream idle time to 5 hr

---

pkg/envoy/lds/connection_manager.go
ws/build.sh

timeout revert

---

init-iptables.sh
ws/build.sh

elastic search iptables fixes

---

init-iptables.sh
ws/build.sh

samba ports added in osm

---

init-iptables.sh
ws/build.sh

nac only mode fixes

---

init-iptables.sh
ws/build.sh

m3db port fix

---

pkg/envoy/lds/response.go
ws/build.sh

fixing an issue with historyd talking to apiserver

---

cmd/osm-controller/osm-controller.go
pkg/catalog/endpoint.go
pkg/catalog/types.go
pkg/catalog/xds_certificates.go
pkg/constants/constants.go
pkg/endpoint/providers/kube/client.go
pkg/endpoint/providers/remote/client.go
pkg/endpoint/providers/remote/errors.go
pkg/endpoint/providers/remote/types.go
ws/build.sh

support for remote AWS gateway-pod

---

pkg/envoy/cds/cluster.go
pkg/envoy/route/config.go
ws/build.sh

multi-instance support 

---

ws/build.sh

osmlatest24cluster tag

---

init/init-iptables.sh
ws/build.sh

Add alertruled port for ES Alerts
**Affected area**:
- New Functionality      [X ]
- Tests                  [ ]
- CI System              [ ]
- Performance            [ ]
No

Add alertruled port

---

init/init-iptables.sh

Remove coral port for alertruled

---

init/init-iptables.sh
ws/build.sh

allowing deviced port to go thru envoy

---

pkg/envoy/route/config.go

Update RouteAction to include 0s timeout, so that request don't timeout.
Resolves: [WS-2240]

15sec timeout fix for syncsend

---

pkg/catalog/ws_http.go
pkg/endpoint/providers/kube/client.go
pkg/envoy/cds/cluster.go
pkg/envoy/cds/response.go
pkg/envoy/cla/cluster_load_assignment.go
pkg/envoy/eds/response.go
pkg/envoy/rds/response.go
pkg/envoy/route/config.go
pkg/kubernetes/util.go
pkg/witesand/catalog.go
pkg/witesand/types.go
ws/build.sh

Please refer to the bug descriptions of 
https://witesandbugz.atlassian.net/browse/WS-2257
https://witesandbugz.atlassian.net/browse/WS-2258
https://witesandbugz.atlassian.net/browse/WS-2259
Resolves: [WS-2258]

Providing pod unicast support

---

pkg/catalog/ws_http.go
pkg/witesand/catalog.go
pkg/witesand/gatewaypods.go
pkg/witesand/types.go
ws/build.sh

[WS-1818] osm changes to get all pods

---

init/init-iptables.sh
ws/build.sh

**Description**:
**Affected area**:
- Tests                  [ ]
- CI System              [ ]
- Performance            [ ]
- no

add osm bypass for vrfserver port in deviced

---

pkg/catalog/ws_http.go
pkg/envoy/cds/cluster.go
pkg/envoy/cds/response.go
pkg/envoy/cla/cluster_load_assignment.go
pkg/envoy/eds/response.go
pkg/envoy/route/config.go
pkg/witesand/catalog.go
pkg/witesand/gatewaypods.go
pkg/witesand/types.go
ws/build.sh

**Description**:
rename gateway to edgepod 
**Affected area**:
- Tests                  [ ]
- CI System              [ ]
- Performance            [ ]
no

[WS-2559] change gateway to edgepod

---

pkg/envoy/cds/response.go
pkg/envoy/lds/connection_manager.go
ws/build.sh

**Description**:
**Affected area**:
- Tests                  [ ]
- CI System              [ ]
- Performance            [ ]

[WS-2655] envoy stream timeout to 20 min

---

pkg/envoy/cds/cluster.go
pkg/envoy/cds/thresholds.go
ws/build.sh

default/policygroupd/9016::default_priority::max_connections::5120
default/policygroupd/9016::default_priority::max_pending_requests::5120
default/policygroupd/9016::default_priority::max_requests::5120
default/policygroupd/9016::default_priority::max_retries::3

[WS-2563]  increase Maxconnections to 5k

---

pkg/catalog/dispatcher.go
pkg/catalog/routes.go
pkg/catalog/service.go
pkg/catalog/ws_http.go
pkg/certificate/rotor/rotor.go
pkg/endpoint/providers/kube/client.go
pkg/endpoint/providers/remote/client.go
pkg/envoy/ads/response.go
pkg/envoy/eds/response.go
pkg/envoy/rds/response.go
pkg/envoy/route/config.go
pkg/injector/webhook.go
pkg/kubernetes/event_handlers.go
pkg/witesand/catalog.go
pkg/witesand/gatewaypods.go
pkg/witesand/types.go
ws/build.sh

Timeout of 1 min for every REST query
remove unwanted logs

[WS-2714] Timeout for queryfunctions
